*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 13 05:42:06 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 07 January 2021 05:15:32
os: Linux-3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/k8s-sample
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15065
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8101 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1858600
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
ModuleNotFoundError: No module named 'NPDR'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 27488, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 27488|app: -1|req: -1/1] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 05:42:08 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 27488|app: -1|req: -1/2] 10.0.0.114 () {54 vars in 1178 bytes} [Wed Jan 13 05:44:01 2021] GET / => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
-- unavailable modifier requested: 22 --
--- no python application found, check your startup logs for errors ---
[pid: 27488|app: -1|req: -1/13] 10.0.0.114 () {54 vars in 1178 bytes} [Wed Jan 13 05:44:16 2021] GET / => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 27488|app: -1|req: -1/14] 10.0.0.114 () {56 vars in 1209 bytes} [Wed Jan 13 05:45:55 2021] GET / => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 13 05:46:41 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 07 January 2021 05:15:32
os: Linux-3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/k8s-sample
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15065
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8101 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb82600
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./k8sSample/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 28114, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/1] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:43 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/2] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:44 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/3] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:46 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/4] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:47 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/5] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:47 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/6] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:47 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/7] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:47 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/8] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:47 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/9] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:48 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/10] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:48 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/11] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:48 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/12] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:48 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/13] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:48 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/14] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:49 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/15] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:46:49 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/16] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:40 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/17] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:41 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/18] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:41 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/19] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:41 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/20] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:41 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/21] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:42 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/22] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:42 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/23] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:42 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/24] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:42 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/25] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:42 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/26] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:43 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/27] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:43 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/28] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:43 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/29] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:43 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/30] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:48:45 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 28114|app: -1|req: -1/31] 10.0.0.114 () {32 vars in 434 bytes} [Wed Jan 13 04:48:54 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jan 13 05:52:09 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 07 January 2021 05:15:32
os: Linux-3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/k8s-sample
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15065
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8101 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xfb5600
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./k8sSample/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 29950, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/1] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:14 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/2] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:15 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/3] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:15 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/4] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:15 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/5] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:15 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/6] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:15 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/7] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:16 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/8] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:16 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/9] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:16 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 29950|app: -1|req: -1/10] 10.0.0.114 () {56 vars in 1243 bytes} [Wed Jan 13 04:52:16 2021] GET /multiclusterapps/ => generated 21 bytes in 0 msecs (HTTP/2.0 500) 2 headers in 83 bytes (0 switches on core 0)
